#!/bin/sh
set -ue
cat package.json | grep "version"
echo ""

npm run build >/dev/null 2>/dev/null
bundle_min_size=$(cat ./dist/preact/iaktta.mjs | wc -c)
bundle_gz_size=$(cat ./dist/preact/iaktta.mjs | gzip | wc -c)

echo "preact build:"
echo "$bundle_min_size bytes minifed"
echo "$bundle_gz_size bytes gzipped"
echo ""
